# Generated by Django 5.0.1 on 2024-02-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0005_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('start', 'start'), ('finish', 'finish'), ('created', 'created')], max_length=50, verbose_name='статус'),
        ),
    ]
