# Generated by Django 5.0.1 on 2024-02-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0006_alter_mail_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ('start_date',), 'permissions': [('set_is_activated', 'Может отключать рассылку')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
